MONGO_URI = "mongodb://localhost:27017" 
MONGO_DB = "crud" 
MONGO_COLLECTION = "books" 
 
PG_HOST = "localhost" 
PG_DATABASE = "book_store" 
PG_USER = "postgres" 
PG_PASSWORD = "abcd" 
PG_PORT = "5432" 
PG_TABLE = "book" 